/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProposalImport } from './routes/proposal'
import { Route as GuestImport } from './routes/guest'
import { Route as DoneImport } from './routes/done'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ProposalRoute = ProposalImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => rootRoute,
} as any)

const GuestRoute = GuestImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRoute,
} as any)

const DoneRoute = DoneImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/done': {
      id: '/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof DoneImport
      parentRoute: typeof rootRoute
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestImport
      parentRoute: typeof rootRoute
    }
    '/proposal': {
      id: '/proposal'
      path: '/proposal'
      fullPath: '/proposal'
      preLoaderRoute: typeof ProposalImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/done': typeof DoneRoute
  '/guest': typeof GuestRoute
  '/proposal': typeof ProposalRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/done': typeof DoneRoute
  '/guest': typeof GuestRoute
  '/proposal': typeof ProposalRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/done': typeof DoneRoute
  '/guest': typeof GuestRoute
  '/proposal': typeof ProposalRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/done' | '/guest' | '/proposal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/done' | '/guest' | '/proposal'
  id: '__root__' | '/' | '/done' | '/guest' | '/proposal'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DoneRoute: typeof DoneRoute
  GuestRoute: typeof GuestRoute
  ProposalRoute: typeof ProposalRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DoneRoute: DoneRoute,
  GuestRoute: GuestRoute,
  ProposalRoute: ProposalRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/done",
        "/guest",
        "/proposal"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/done": {
      "filePath": "done.tsx"
    },
    "/guest": {
      "filePath": "guest.tsx"
    },
    "/proposal": {
      "filePath": "proposal.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
